### ISSUE TITLE
Need help building for Ubuntu running on a Pi 4

### ISSUE THREAD

**Issue by FlexMcMurphy** [rursache/Tvheadend-arm64#1]
Hello,

Thank you for these steps to build TVHeadend. I have a question please.
I am running Ubuntu server 22.04 on a Pi 4.
```
ubuntu@ubuntu:~$ uname -a
Linux ubuntu 5.15.0-1015-raspi #17-Ubuntu SMP PREEMPT Mon Sep 12 13:14:51 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
```

What build target should I choose for that OS? I don't see a good match on the [tvheadend github autobuild scripts](https://github.com/tvheadend/tvheadend/tree/master/Autobuild) page.

Possibly bullseye-arm64.sh? Or maybe xenial-arm64.sh will still work?

Also, apparently this takes about an hour to build on a Pi. Would you know how to build tvheadend on another computer but to run on the Ubuntu Pi? I guess I'm talking about cross-compiling? I have a much faster intel laptop running Manjaro. Maybe I can build tvheadend on that to run on the Pi?

Cheers,

Flex

**Comment by rursache** [comment]
hi, i don't have experience with compiling on ubuntu or anything else but bullseye. i migrated to docker to avoid all this mess. compiling on my rpi4 took around 38-40 minutes on bullseye. i still recommend to use docker tho
